Update build_ci.yml

diff --git a/.github/workflows/build_ci.yml b/.github/workflows/build_ci.yml
--- a/.github/workflows/build_ci.yml
+++ b/.github/workflows/build_ci.yml
@@ -102,10 +102,10 @@ jobs:
       #     Write-Host "[+] Verifying CodeQL installation..."
       #     & $env:CODEQL_BIN --version
 
-      # - name: Install Nuget Packages
-      #   run: |
-      #     cd "$env:WDS_PATH"
-      #     nuget restore .\packages.config -PackagesDirectory .\packages\
+      - name: Install Nuget Packages
+        run: |
+          cd "$env:WDS_PATH"
+          nuget restore .\packages.config -PackagesDirectory .\packages\
       #     dir
 
       # - name: Initialize CodeQL Packs
@@ -131,6 +131,28 @@ jobs:
       #         Write-Error "[!] Database creation failed with error $LASTEXITCODE"
       #         exit $LASTEXITCODE
       #     }
+
+      # - name: Creating CodeQL Database & Build Drivers
+      #   shell: pwsh
+      #   run: |
+      #     Write-Host "[+] Creating CodeQL Database..."
+
+      #     # Use & (call operator) with $env: variables
+      #     & $env:CODEQL_BIN database create "$env:X64_DB_PATH" `
+      #         --language=cpp `
+      #         --command "pwsh -NoProfile -ExecutionPolicy Bypass -Command `"cd '$env:WDS_PATH'; ./Build-AllSamples.ps1 -Configuration Release -Platform x64 -Verbose`""
+
+      #     if ($LASTEXITCODE -ne 0) {
+      #         Write-Error "[!] Database creation failed with error $LASTEXITCODE"
+      #         exit $LASTEXITCODE
+      #     }
+
+      - name: Build Drivers
+        run: ./Build-AllSamples.ps1 -Configuration ${{ env.CONFIG }} -Platform ${{ env.PLATFORM }} -Verbose
+        # env:
+        #   WDS_Configuration: ${{ matrix.configuration }}
+        #   WDS_Platform: ${{ matrix.platform }}
+        #   WDS_ReportFileName: _overview.${{ matrix.configuration }}.${{ matrix.platform }}
 
       - name: Print Driver Data JSON
         shell: pwsh
