Update build_ci.yml

diff --git a/.github/workflows/build_ci.yml b/.github/workflows/build_ci.yml
--- a/.github/workflows/build_ci.yml
+++ b/.github/workflows/build_ci.yml
@@ -3,10 +3,7 @@ name: Build Drivers
 on:
   workflow_call:
     inputs:
-      arch:
-        required: true
-        type: string
-      config:
+      platform:
         required: true
         type: string
 
@@ -16,6 +13,8 @@ jobs:
 
     env:
       WDS_PATH: "${{ github.workspace }}\\windows-driver-samples"
+      Platform: "${{ inputs.platform }}"
+      Config: "Release"
 
     steps:
       - name: Checkout NS
@@ -54,7 +53,7 @@ jobs:
           Remove-Item "serial" -Recurse -Force -ErrorAction SilentlyContinue
           Remove-Item "setup" -Recurse -Force -ErrorAction SilentlyContinue
           Remove-Item "simbatt" -Recurse -Force -ErrorAction SilentlyContinue
-          Remove-Item "smartcrd" -Recurse -Force -ErrorAction SilentlyContinue
+          Remove-Itedm "smartcrd" -Recurse -Force -ErrorAction SilentlyContinue
           Remove-Item "spb" -Recurse -Force -ErrorAction SilentlyContinue
           Remove-Item "storage" -Recurse -Force -ErrorAction SilentlyContinue
           Remove-Item "thermal" -Recurse -Force -ErrorAction SilentlyContinue
@@ -65,14 +64,12 @@ jobs:
           Remove-Item "wia" -Recurse -Force -ErrorAction SilentlyContinue
           Remove-Item "wmi" -Recurse -Force -ErrorAction SilentlyContinue
 
-      - name: Export JSON as env var
+      - name: Load Driver Data JSON
         shell: pwsh
         run: |
           $jsonPath = Join-Path $Env:GITHUB_WORKSPACE "driver-data.json"
           Write-Host "Reading JSON from: $jsonPath"
-
-          $Platform = "${{ inputs.arch }}"
-          $Config   = "${{ inputs.config }}"
+          Write-Host ">>$Platform, $Config"
 
           $json = Get-Content $jsonPath -Raw
           $json = $ExecutionContext.InvokeCommand.ExpandString($json)
@@ -83,8 +80,56 @@ jobs:
           Add-Content $Env:GITHUB_ENV $driverJson
           Add-Content $Env:GITHUB_ENV "EOF"
 
+      # - name: Download and Extract CodeQL CLI
+      #   shell: pwsh
+      #   run: |
+      #     $CodeqlZip = "codeql-win64.zip"
+      #     $DownloadUrl = "https://github.com/github/codeql-cli-binaries/releases/download/v2.15.4/codeql-win64.zip"
 
-      - name: Download and Extract CodeQL CLI
+      #     Write-Host "[+] Downloading CodeQL CLI v2.15.4..."
+      #     curl.exe -L -o $CodeqlZip $DownloadUrl
+
+      #     Write-Host "[+] Extracting CodeQL..."
+      #     # tar is built-in to Windows Server 2022
+      #     tar.exe -xf $CodeqlZip
+
+      #     Write-Host "[+] Cleaning up zip..."
+      #     Remove-Item $CodeqlZip
+
+      #     Write-Host "[+] Verifying CodeQL installation..."
+      #     & $env:CODEQL_BIN --version
+
+      # - name: Install Nuget Packages
+      #   run: |
+      #     cd "$env:WDS_PATH"
+      #     nuget restore .\packages.config -PackagesDirectory .\packages\
+      #     dir
+
+      # - name: Initialize CodeQL Packs
+      #   shell: pwsh
+      #   run: |
+      #     Write-Host "[+] Download Pack microsoft/windows-drivers@1.0.13..."
+      #     & $env:CODEQL_BIN pack download microsoft/windows-drivers@1.0.13
+
+      #     Write-Host "[+] Download Pack codeql/cpp-queries@0.9.0..."
+      #     & $env:CODEQL_BIN pack download codeql/cpp-queries@0.9.0
+
+      # - name: Creating CodeQL Database & Build Drivers
+      #   shell: pwsh
+      #   run: |
+      #     Write-Host "[+] Creating CodeQL Database..."
+
+      #     # Use & (call operator) with $env: variables
+      #     & $env:CODEQL_BIN database create "$env:X64_DB_PATH" `
+      #         --language=cpp `
+      #         --command "pwsh -NoProfile -ExecutionPolicy Bypass -Command `"cd '$env:WDS_PATH'; ./Build-AllSamples.ps1 -Configuration Release -Platform x64 -Verbose`""
+
+      #     if ($LASTEXITCODE -ne 0) {
+      #         Write-Error "[!] Database creation failed with error $LASTEXITCODE"
+      #         exit $LASTEXITCODE
+      #     }
+
+      - name: Print Driver Data JSON
         shell: pwsh
         run: |
           $json = $Env:DRIVER_DATA
